analyzer/analyzer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

analyzer/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.IndexView, name='index'),
    path('bbsr/', views.BbsrView, name='bbsr'),
    path('agra/', views.AgraView, name='agra'),
    path('bbsr/market/', views.BbsrMarket, name='bbsrmarket'),
    path('bbsr/food/', views.BbsrFood, name='bbsrfood'),
    path('bbsr/places/', views.BbsrPlaces, name='bbsrplaces'),
    path('bbsr/Weather/', views.BbsrWeather, name='bbsrweather'),
    path('bbsr/Crime/', views.BbsrCrime, name='bbsrcrime'),
    path('agra/market/', views.AgraMarket, name='agramarket'),
    path('agra/food/', views.AgraFood, name='agrafood'),
    path('agra/places/', views.AgraPlaces, name='agraplaces'),
    path('agra/Weather/', views.AgraWeather, name='agraweather'),
    path('agra/Crime/', views.AgraCrime, name='agracrime')
]

analyzer/core/models.py
from django.db import models

# Create your models here.

analyzer/core/views.py
from django.shortcuts import render


def IndexView(request):
    return render(request, 'core/index.html')

def BbsrView(request):
    return render(request, 'core/bbsr.html')

def AgraView(request):
    return render(request, 'core/agra.html')

def BbsrMarket(request):
    return render(request, 'bbsr/market.html')

def BbsrFood(request):
    return render(request, 'bbsr/food.html')

def BbsrPlaces(request):
    return render(request, 'bbsr/places.html')

def BbsrWeather(request):
    return render(request, 'bbsr/weather.html')

def BbsrCrime(request):
    return render(request, 'bbsr/crime.html')



def AgraMarket(request):
    return render(request, 'agra/market.html')

def AgraFood(request):
    return render(request, 'agra/food.html')

def AgraPlaces(request):
    return render(request, 'agra/places.html')

def AgraWeather(request):
    return render(request, 'agra/weather.html')

def AgraCrime(request):
    return render(request, 'agra/crime.html')

analyzer/core/templates/agra/crime.html
<!Doctype html>
{% load staticfiles %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>Crime Analysis</title>




    <script>
window.onload = function () {

var chart = new CanvasJS.Chart("pie", {
  exportEnabled: true,
  animationEnabled: true,
  title:{
    text: "Crime In India"
  },
  legend:{
    cursor: "pointer",
    itemclick: explodePie
  },
  data: [{
    type: "pie",
    showInLegend: true,
    toolTipContent: "{name}: <strong>{y}%</strong>",
    indexLabel: "{name} - {y}%",
    dataPoints: [
      { y: 14, name: "Andhra Pradesh", exploded: true },
      { y: 11, name: "TamilNadu" },
      { y: 8, name: "Punjab" },
      { y: 8, name: "Odisha" },
      { y: 3, name: "Maharashtra" },
      { y: 5, name: "Kerala" },
      { y: 11, name: "Karnataka"},
      { y: 5, name: "Gujarat" },
      { y: 5, name: "Goa" },
      { y: 8, name: "Bihar" },
      { y: 8, name: "Assam" }
    ]
  }]
});
chart.render();
}

function explodePie (e) {
  if(typeof (e.dataSeries.dataPoints[e.dataPointIndex].exploded) === "undefined" || !e.dataSeries.dataPoints[e.dataPointIndex].exploded) {
    e.dataSeries.dataPoints[e.dataPointIndex].exploded = true;
  } else {
    e.dataSeries.dataPoints[e.dataPointIndex].exploded = false;
  }
  e.chart.render();

}
</script>





  </head>
  <body>

    <!-- NAVBAR -->
<nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href={% url 'core:index' %}>Home</a></li>
          <li class="breadcrumb-item"><a href={% url 'core:agra' %}>Agra</a></li>
          <li class="breadcrumb-item active" aria-current="page">Crime</li>
        </ol>
      </nav>

      <div class="container-fluid mt-5 ">
        <div id="pie" style="height: 470px; width: 100%;"></div>
        <br><br>
        <div class="container">
          <img src="{% static 'img/agracrime.png' %}" style="height: 600px; width: auto">
        </div>
      </div>





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
  </body>
</html>

analyzer/core/templates/agra/food.html
<!DOCTYPE HTML>
{% load staticfiles %}

<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>
            .write-ups{
                transform: scale(1.05);
                color: white;
                background-color: rgba(7, 7, 59, 0.897);
                transition: 0.5s ease-in;
                box-shadow:2px 8px 3px black;
                width:70%; 
                border:1px solid rgb(29, 26, 26);
                padding:10px;
                transition: 0.3s linear;
                justify-content: center;
                margin-left: 150px;
                margin-bottom:90px;
                cursor: crosshair; 
            }
            .write-ups:hover{
                transform: scale(1.09);
                transition-delay: 0.2s;
               
                box-shadow: 2px 10px 7px black;
    
            }
        </style>
    
<script>

/*Market Analysis Main graph function*/
window.onload = function () {
/*North Indian Cuisine function*/
var chart1 = new CanvasJS.Chart("north", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "North Indian Cuisine"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#6B8E23",
        dataPoints: [
{ y: 3.9, label: "Jahanpanah" },
{ y: 4.2, label: "Pinch Of Spice" },
{ y: 4.0, label: "Momo Cafe" },
{ y: 4.3, label: "Peshwari - ITC Mughal" },
{ y: 3.8, label: "Dawat-e-Nawab-Radisson Blu" },
{ y: 3.9, label: "The Latitude-Radisson Blu" },
{ y: 3.4, label: "The Charcoal Chimney" },
{ y: 4.9, label: "sheroes Hangout" },
{ y: 3.8, label: "Bon Barbecue" },
{ y: 3.9, label: "Chapter 1 Cafe" },
{ y: 3.7, label: "Pind Balluchi" },
{ y: 4.2, label: "Tea’se Me-Rooftop Tea Boutique" }
]
    }]
});
/*chinese graph function*/
var chart2 = new CanvasJS.Chart("chinese", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Chinese Cuisine"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#BA55D3",
        dataPoints: [
{ y: 4.2, label: "Pinch Of Spice" },
{ y: 3.9, label: "The Latitude - Radisson Blu" },
{ y: 3.4, label: "The Charcoal Chimney" },
{ y: 4.9, label: "Sheroes Hangout" },
{ y: 3.8, label: "Bon Barbecue" },
{ y: 4.2, label: "Tea’se Me- Rooftop Tea Boutique" }
]
    }]
});

/*continental graph function*/

var chart3 = new CanvasJS.Chart("continental", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Continental Cuisine"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#008B8B",
        dataPoints: [
{ y: 3.9, label: "The Latitude - Radisson Blu" },
{ y: 3.4, label: "The Charcoal Chimney" },
{ y: 3.8, label: "Bon Barbecue" },
{ y: 3.9, label: "Chapter 1 Cafe" },
{ y: 4.2, label: "Tea’se Me - Rooftop Tea Boutique" }
]
    }]
});

/*italian graph function*/

var chart4 = new CanvasJS.Chart("italian", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Italian Cuisine"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#FF1493",
        dataPoints: [
{ y: 3.9, label: "Chapter ! Cafe" },
{ y: 4.4, label: "Pizza Hut" },
{ y: 4.2, label: "Tea’se Me - Rooftop Tea Boutique" }
]
      }]
    });


/*mughlai graph function*/

var chart5 = new CanvasJS.Chart("mughlai", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Mughlai Cuisine"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#483D8B",
        dataPoints: [
{ y: 3.9, label: "Jahanpanah" },
{ y: 3.5, label: "Rangrezz Restaurant" },
{ y: 4.2, label: "Pinch Of Spice" },
{ y: 4.3, label: "Peshwri - ITC Mughal" },
{ y: 4.0, label: "Taj Bano - ITC Mughal" },
{ y: 3.6, label: "G Thal" },
{ y: 3.8, label: "Dawat-E-Nawab- Radisson Blu" },
{ y: 3.4, label: "The Charcoal Chimney" },
{ y: 3.7, label: "Pind Balluchi" }
]
      }]
    });


/*cafe graph function*/

var chart6 = new CanvasJS.Chart("cafe", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Cafe"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#6B8E23",
        dataPoints: [
{ y: 4.9, label: "Sheroes Hangout" },
{ y: 3.9, label: "Chapter 1 Cafe" }
]
      }]
    });



/*Rajasthani graph function*/

var chart7 = new CanvasJS.Chart("rajasthani", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Rajasthani Cuisine"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#BA55D3",
        dataPoints: [
{ y: 4.00, label: "Chokho Jeeman Marwari Jain Bhojanalya" },
{ y: 3.60, label: "G Thal" }
]
      }]
    });

/*Average Cost Function*/
var chart8 = new CanvasJS.Chart("averagecost", {
    animationEnabled: true,
    theme: "light2", // "light1", "light2", "dark1", "dark2"
    title:{
        text: "Average Cost for 2"
    },
    axisY: {
        title: "INR"
    },
    data: [{
        type: "column",
        dataPoints: [
{ y: 683.33, label: "Agra Cantt" },
{ y: 700, label: "Civil Lines" },
{ y: 2000, label: "Courtyard By Marriott Agra" },
{ y: 2500, label: "ITC Mughal,Tajganj" },
{ y: 800, label: "Khandari" },
{ y: 1800, label: "Radisson Blu,Tajganj" },
{ y: 550, label: "Rakabganj" },
{ y: 737.5, label: "Tajganj" },
]
    }]
});


chart1.render()
chart2.render()
chart3.render()
chart4.render()
chart5.render()
chart6.render()
chart7.render()
chart8.render();
}
</script>


</head>

<!-- NAVBAR -->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href={% url 'core:index' %}>Home</a></li>
    <li class="breadcrumb-item"><a href={% url 'core:agra' %}>Agra</a></li>
    <li class="breadcrumb-item active" aria-current="page">Food</li>
  </ol>
</nav>

<body>

        <div class="container">
                <div  class="graph-heading">
                        <h3 style="margin-bottom:0;" class="text-underline-primary mb-5 text-center display-3">AGRA FOOD ANALYSIS</h3>
                        <hr style="width:30%; margin-top:2px; height:40px; border-top: 4px double #8c8b8b;
                        text-align: center;">
                    </div>
        

<div class="container">
  <!-- Main graph -->
  <!-- <div id="MainGraph" style="height: 370px; width: 70%;"></div> -->


  <!-- Average Cost for 2 -->
  <div id="averagecost" style="height: 370px; width: 100%;"></div>
  <h4  class=" write-ups mb-5 ">The graph showing cost for food for 2 person in different locality, Rakabganjh is found to be comparatively cheapest with affordable restaurants and ITC Mughal,Tajganj to be expensive with expensive restaurants.</h4>

 

  <!-- North Indian -->
  <div id="north" style="height: 300px; width: 100%; margin-bottom:60px;"></div>

  <!-- Chinese -->
  <div id="chinese" style="height: 300px; width: 100%; margin-bottom:60px;"></div>

  <!-- Continental -->
  <div id="continental" style="height: 300px; width: 100%; margin-bottom:60px;"></div>

  <!-- Italian -->
  <div id="italian" style="height: 300px; width: 100%; margin-bottom:60px;"></div>

  <!-- Mughlai -->
  <div id="mughlai" style="height: 300px; width: 100%; margin-bottom:60px;"></div>

  <!-- Cafe -->
  <div id="cafe" style="height: 300px; width: 100%; margin-bottom:60px;"></div>

  <!-- Rajasthani -->
  <div id="rajasthani" style="height: 300px; width: 100%; margin-bottom:60px;"></div>

  


</div>



<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</body>
</html>

analyzer/core/templates/agra/market.html
<!DOCTYPE HTML>
{% load staticfiles %}

<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>
            .write-ups{
                transform: scale(1.05);
                color: white;
                background-color: rgba(7, 7, 59, 0.897);
                transition: 0.5s ease-in;
                box-shadow:2px 8px 3px black;
                width:70%; 
                border:1px solid rgb(29, 26, 26);
                padding:10px;
                transition: 0.3s linear;
                justify-content: center;
                margin-left: 150px;
                margin-bottom:60px;
                cursor: crosshair; 
            }
            .write-ups:hover{
                transform: scale(1.09);
                transition-delay: 0.2s;
               
                box-shadow: 2px 10px 7px black;
    
            }
        </style>
<script>

/*Market Analysis Main graph function*/
window.onload = function () {

var chart1 = new CanvasJS.Chart("MainGraph", {
    animationEnabled: true,

    title:{
        // text:"Agra Market Analysis"
    },
    axisX:{
        interval: 1
    },
    axisY2:{
        interlacedColor: "rgba(1,77,101,.2)",
        gridColor: "rgba(1,77,101,.1)",
        title: "Ratings out of 5"
    },
    data: [{
        type: "bar",
        name: "companies",
        axisYType: "secondary",
        color: "#014D65",
        dataPoints: [
{ y: 4.0, label: "Agra Art Gallery" },
{ y: 4.0, label: "Shahin Arts" },
{ y: 3.5, label: "Sadar Bazaar" },
{ y: 4.0, label: "Kinari Bazaar" },
{ y: 5.0, label: "Shilpgram" },
{ y: 3.7, label: "Saket Mall" },
{ y: 4.6, label: "The Warehouse of Gifts and Souvenirs" },
{ y: 3.4, label: "Kashmiri Bazar" },
{ y: 4.5 , label: "Marble Handicrafts" },
{ y: 4.7, label: "kailash Plaza" },
{ y: 3.8, label: "Gems and Arts Gallery" },
{ y: 4.0, label: "Mughal Carpet" },
{ y: 4.0, label: "Big Bazaar Ratan Mall" },
{ y: 4.1, label: "Subhash Emporium" }
]
    }]
});

/*Clothing graph function*/
var chart2 = new CanvasJS.Chart("clothing", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Clothing"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Market Name"
    },
    data: [{
        type: "line",
        color: "#B0C4DE",
        dataPoints: [
{ y: 4.0, label: "Big Bazaar Ratan Mall" },
{ y: 4.7, label: "kailash Plaza" },
{ y: 3.7, label: "Saket Mall" },
{ y: 4.0, label: "Kinari Bazaar" },
{ y: 3.5, label: "Sadar Bazaar" }
]
    }]
});
/*handicraft graph function*/
var chart3 = new CanvasJS.Chart("handicraft", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Handicrafts"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#008080",
        dataPoints: [
{ y: 4.0, label: "Mughal Carpet" },
{ y: 4.7, label: "Kailash Plaza" },
{ y: 3.4, label: "Kashmiri Bazar" },
{ y: 5.0, label: "Shilpgram" },
{ y: 4.0, label: "Shahin Arts" }
]
    }]
});

/*Household Shops function*/

var chart4 = new CanvasJS.Chart("household", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Household Shops"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#000000",
        dataPoints: [
{ y: 4.0, label: "Big Bazar Ratan Mall" },
{ y: 4.0, label: "Mughal Carpet" },
{ y: 4.7, label: "kailash Plaza" },
{ y: 4.6, label: "The Warehouse of Gifts and Souvenirs" },
{ y: 3.7, label: "Saket Mall" }
]
    }]
});

/*agra special graph function*/



var chart5 = new CanvasJS.Chart("special", {
    animationEnabled: true,
    theme: "light2",
    title:{
       
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#FF4500",
        dataPoints: [
{ y: 4.0, label: "Mughal Carpet" },
{ y: 3.8, label: "Gems and Arts Gallery" },
{ y: 4.5 , label: "Marble Handicrafts" },
{ y: 3.4, label: "Kashmiri Bazar" },
{ y: 5.0, label: "Shilpgram" },
{ y: 4.0, label: "Shahin Arts" },
{ y: 4.0, label: "Agra Art Gallery" }
]
      }]
    });


/*Showpieces function*/

var chart6 = new CanvasJS.Chart("showpiece", {
    animationEnabled: true,
    theme: "light2",
    title:{
        text: "Showpieces"
    },
    axisY:{
        title: "Ratings",
        includeZero: false
    },
    axisX:{
        title: "Venue"
    },
    data: [{
        type: "line",
        color: "#8B4513",
        dataPoints: [
{ y: 4.1, label: "Subhash Emporium" },
{ y: 4.0, label: "Big Bazaar Ratan Mall" },
{ y: 4.0, label: "Mughal Carpet" },
{ y: 3.8, label: "Gems and Arts Gallery" },
{ y: 4.7, label: "kailash Plaza" },
{ y: 4.5 , label: "Marble Handicrafts" },
{ y: 4.6, label: "The Warehouse of Gifts and Souvenirs"},
{ y: 4.0, label: "Agra Art Gallery" }
]
    }]
});



chart1.render()
chart2.render()
chart3.render()
chart4.render()
chart5.render()
chart6.render();
}
</script>


</head>

<!-- NAVBAR -->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href={% url 'core:index' %}>Home</a></li>
    <li class="breadcrumb-item"><a href={% url 'core:agra' %}>Agra</a></li>
    <li class="breadcrumb-item active" aria-current="page">Market</li>
  </ol>
</nav>
<div class="container">
        <div  class="graph-heading">
                <h2 style="margin-bottom:10PX;" class="text-underline-primary mb-5 text-center display-2">AGRA MARKET ANALYSIS</h2>
                <hr style="width:30%; margin-top:2px; height:40px; border-top: 4px double #8c8b8b;
                text-align: center;">
            </div>

<body>
<div class="container">
  <!-- Main graph -->
  <div id="MainGraph" style="height: 370px; width: 100%;"></div>
  

  <!-- clothing graph -->
  <div id="clothing" style="height: 370px; width: 100%; margin-top: 50px;"></div>
  <h4  class=" write-ups mb-5 ">If you like to shop clothes Agra gives a number of options. Most famous is Kailash Plaza which is having all the famous brand shops .</h4>


  <!-- Handicrafts graph -->
  <div id="handicraft" style="height: 370px; width: 100%;"></div>
  <h4  class=" write-ups mb-5 ">If you love handicrafts then Agra is one of the best place to visit. Handicraft market called "Shilpgram" is best to visit in Agra for  Handicraft.</h4>


  <!-- Household Shops graph -->
  <div id="household" style="height: 370px; width: 100%;"></div>
  <h4  class=" write-ups mb-5 ">Household  shopping is a must, and if it is from a historical city who won't be pleased to do it. For Household shopping Kailash Plaza is the best.</h4>


  <!-- Agra Special graph -->
  <div id="special" style="height: 370px; width: 100%;"></div>
  <h4  class=" write-ups mb-5 ">If you love handicrafts then Agra is one of the best Agra place to visit. Handicraft market called "Shilpgram" is best to visit in Agra for  Handicraft.
        A historical city of India, which witnessed various changing courses of history must be having it's own speciality, and if it's goods who won't want to buy 
        it.FOr Agra Special market called "Shilpgram" is best.</h4>


  <!-- Showpieces graph -->
  <div id="showpiece" style="height: 370px; width: 100%;"></div>
  <h4  class=" write-ups mb-5 ">If you love showpieces then Agra has various shops. Most famous is Kailash Plaza.</h4>

</div>


<!-- Table -->
<!-- <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Market Name</th>
      <th scope="col">Ratings</th>
      <th scope="col">Address</th>
      <th scope="col">Famous For</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Market building</td>
      <td>4.3</td>
      <td>Bhubaneshwar Marg, Unit-2, Ashok Nagar</td>
      <td>Fashion wears, Accessories, Footwear</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Reliance Trends</td>
      <td>4.3</td>
      <td>First Floor,Khata No.444, Kharabela Nagar</td>
      <td>Fashion wears, Accessories, Footwear</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Esplanade</td>
      <td>4.6</td>
      <td>Puri-Cuttak Rd, Rasulgarh Industrial Estate</td>
      <td>Fashion wears, Accessories, Footwear, Food</td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td>BMC Keshari</td>
      <td>4.2</td>
      <td>2nd St, Unit-2, Ashok Nagar</td>
      <td>Fashion wears, Accessories, Footwear</td>
    </tr>
    <tr>
      <th scope="row">5</th>
      <td>Big Bazar</td>
      <td>4.3</td>
      <td>Forum Mart, 89, Unit 3, Kharabela Nagar</td>
      <td>Fashion wears, Accessories, Footwear, Food</td>
    </tr>
    <tr>
      <th scope="row">6</th>
      <td>Saree Mandir</td>
      <td>3.9</td>
      <td>Master Canteen Area, Kharabela Nagar, Bhubaneswar</td>
      <td>Sarees</td>
    </tr>
    <tr>
      <th scope="row">7</th>
      <td>Pal Heights</td>
      <td>4.2</td>
      <td>Nandankanan Rd, j-7,Jayadev Vihar</td>
      <td>Fashion wears, Accessories, Footwear, Food</td>
    </tr>

  </tbody>
</table> -->
<!-- End table -->


<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</body>
</html>

analyzer/core/templates/core/navbar.html
{% load staticfiles %}
    <nav style=" box-shadow: 2px 3px 4px #362424;" class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a style="color:black" class="navbar-brand text-dark" href={% url 'core:index' %}><h5 class="display-5 pt-2">Home</h6></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto  justify-content-end">


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select City
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href={% url 'core:agra' %} ><h6 class="display-6  ">Agra</h6></a>
                <a class="dropdown-item" href={% url 'core:bbsr' %} ><h6 class="display-6 ">Bhubaneswar</h6></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>

            <li class="nav-item justify-content-center">
                <a class="nav-link" href="#team-section">Our Team</a>
              </li>

          </ul>
          <form class="form-inline my-2 my-lg-0">
            
              <a href="https://goo.gl/forms/E6x5YbmvTuvC9N3J2" target="_blank" class=" btn btn-outline-primary  ">Review Your Visit</a
          </form>
        </div>
      </nav>